- .devcontainer/docker-compose.yaml
- .env.sample
- .github/workflows/app-tests.yaml
- .vscode/settings.json
- src/fastapi_app/api_routes.py
This pull request primarily focuses on two areas: updating the PostgreSQL username from `postgres` to `admin` across multiple files, and adding new features to the FastAPI application in `src/fastapi_app/api_routes.py`.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
> Add more API routes

- docs/README.md
The goal is for the samples browser to pick up this readme.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
> Add extra README

- .github/workflows/azure-dev.yaml
- azure.yaml
Adds azd pipeline as required.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
> Add pipeline

- src/fastapi_app/__init__.py
- src/fastapi_app/openai_clients.py
- src/fastapi_app/postgres_engine.py
- src/fastapi_app/query_rewriter.py
- src/requirements.txt
This should help with token refresh, though I need to research again when exactly do_connect is called and if this is resetting too often (I could look at the token expiry).
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
> Update token in do_connect event

- src/fastapi_app/query_rewriter.py
- src/fastapi_app/rag_advanced.py
It appears that gpt-3.5-turbo 0613 doesn't specify required parameters as reliably as newer models, especially with other parameters being specified, which was breaking calls that involved filters. So this change means it will always default to the original user_query if no search_query was found in the parameters.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
See [CONTRIBUTING.md](https://github.com/Azure-Samples/rag-postgres-openai-python/blob/main/CONTRIBU …
> Workaround for older model that doesnt specify required param

- azure.yaml
This insures that the static frontend folder is included in the docker container.
fix #53 
related https://github.com/Azure/azure-dev/issues/3546, https://github.com/Azure/azure-dev/issues/4136
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
- [-] The current tests all pass (`python -m pytest`).
- [-] I added tests that prove …
> Fix azd Stage

- .github/workflows/app-tests.yaml
- tests/conftest.py
Per suggestion in https://github.com/microsoft/playwright-python/issues/2506
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
> Try removing clear=True to fix Playwright tests on Windows

- src/backend/entrypoint.sh
Fixes deployment error:
"The TargetPort 8000 is bound to an inaccessible loopback IP address, bind to a non-loopback IP address instead."
> Update entrypoint.sh - Add --host 0.0.0.0 to Uvicorn execution

- infra/main.parameters.json
Unblock azd up --no-prompt by setting AZURE_OPENAI_LOCATION in env.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
N/A
* PF tested with a brand new env, it still prompts for location in that case.
> allow setting AZURE_OPENAI_LOCATION in env

- docs/customize_data.md
- src/backend/fastapi_app/postgres_models.py
These changes make it easier to bring in your own data.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
> Model schema changes

- .github/workflows/app-tests.yaml
- README.md
- docs/using_entra_auth.md
Adding page about Entra-based auth to PG tools. Will add PGadmin next.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
N/A
> Add entra auth

- azure.yaml
- infra/main.bicep
- pyproject.toml
- requirements-dev.txt
- scripts/pre_down.ps1
- scripts/pre_down.py
- scripts/pre_down.sh
Fixes #95 by adding pre-down scripts to delete GlobalStandard OpenAI deployments.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
> Add pre_down scripts to delete GlobalStandard deployments

- .github/workflows/app-tests.yaml
- .github/workflows/evaluate.yaml
- src/backend/fastapi_app/__init__.py
- src/backend/fastapi_app/prompts/query.txt
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
> Test evaluate

- .github/workflows/app-tests.yaml
- .github/workflows/evaluate.yaml
And test eval
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
> Remove unused code in workflow 

- .github/workflows/app-tests.yaml
I will bring back 3.11, 3.12, and perhaps 3.13, after GitHub U workshop.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
N/A
> Remove python versions for faster CI

- scripts/setup_postgres_azurerole.ps1
- scripts/setup_postgres_azurerole.sh
- scripts/setup_postgres_database.ps1
- scripts/setup_postgres_database.sh
- scripts/setup_postgres_seeddata.ps1
- scripts/setup_postgres_seeddata.sh
- src/backend/fastapi_app/postgres_engine.py
- src/backend/fastapi_app/setup_postgres_azurerole.py
- src/backend/fastapi_app/setup_postgres_database.py
- src/backend/fastapi_app/setup_postgres_seeddata.py
This fixes two issues experienced in Codespaces.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
> Fix tenant_id and sslmode for post-provision scripts

- .vscode/settings.json
- src/backend/fastapi_app/postgres_engine.py
Fixes issue with new env
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
> Fix for vector extension order

- evals/eval_config.json
- evals/evaluate.py
- src/backend/fastapi_app/api_models.py
- src/backend/fastapi_app/rag_advanced.py
- src/backend/fastapi_app/rag_base.py
- src/backend/fastapi_app/rag_simple.py
This pull request introduces several changes to add a new metric for evaluating citation matches and to incorporate a random seed for reproducibility in various functions. The most important changes include adding the new `CitationsMatchedMetric` class, updating configuration files to include the new metric, and modifying functions to accept and use a seed parameter.
* [`evals/eval_config.json`](diffhunk://#diff-4adb0af781fab559b88e413b18255bc068739bc61d4cf39f137700ac43fb87eaL4-R12): Updated the `requested_metrics` to include `"citations_matched"` and added a `seed` parameter in `target_parameters`.
* [`evals/evaluate.py`](diffhunk://#diff-94211c0749af47fbe4014baa2813a32093b8d3a2ca04a84417f856b93dfe4074R4-R41): Added the `CitationsMatchedMetric` class to compute the percentage of …
> Add seed parameter (optional) and custom evaluation metric for citations overlap

- .github/workflows/evaluate.yaml
This pull request includes updates to the GitHub Actions workflow to enhance the evaluation process for pull requests. Key changes include modifying the conditions under which the evaluation job runs, removing an unnecessary step, and adding a new step to commit and push evaluation results.
Changes to evaluation conditions and steps:
* [`.github/workflows/evaluate.yaml`](diffhunk://#diff-c13bb9112390fbf0c4f2fd7cafeed0357996509af5da617df205c035d6c04405L17-R20): Updated the `if` condition to ensure only authorized users can trigger the evaluation by checking the `author_association` and matching the comment body to `/evaluate`.
* [`.github/workflows/evaluate.yaml`](diffhunk://#diff-c13bb9112390fbf0c4f2fd7cafeed0357996509af5da617df205c035d6c04405L44-L47): Removed the step that checks for the …
> Push results to branch

- .github/workflows/evaluate.yaml
This pull request includes updates to the GitHub Actions workflow configuration to streamline the checkout and commit processes.
Changes to workflow configuration:
* [`.github/workflows/evaluate.yaml`](diffhunk://#diff-c13bb9112390fbf0c4f2fd7cafeed0357996509af5da617df205c035d6c04405L59-R65): Updated the step to checkout the pull request using the `hub` command and environment variables for better integration with GitHub Actions.
* [`.github/workflows/evaluate.yaml`](diffhunk://#diff-c13bb9112390fbf0c4f2fd7cafeed0357996509af5da617df205c035d6c04405L196-R206): Removed the step to get the PR branch name and simplified the commit and push process.
If you're not sure, try it out on an old …
> Use a different way to push results in eval workflow

- .github/workflows/evaluate.yaml
This pull request includes changes to the `.github/workflows/evaluate.yaml` file to improve the workflow for checking out pull requests and the default branch.
Workflow improvements:
* [`.github/workflows/evaluate.yaml`](diffhunk://#diff-c13bb9112390fbf0c4f2fd7cafeed0357996509af5da617df205c035d6c04405L59-R63): Changed the job name from "Checkout pull request" to "Checkout default branch" and updated the action to `actions/checkout@v4`.
* [`.github/workflows/evaluate.yaml`](diffhunk://#diff-c13bb9112390fbf0c4f2fd7cafeed0357996509af5da617df205c035d6c04405L59-R63): Updated the step to check out the actual pull request using `gh pr checkout` instead of `hub pr checkout`.
If you're not sure, …
> Use gh cli instead of hub

- .devcontainer/docker-compose.yaml
- .github/workflows/app-tests.yaml
- README.md
- evals/generate_ground_truth.py
- pyproject.toml
- src/backend/fastapi_app/__init__.py
- src/backend/fastapi_app/api_models.py
- src/backend/fastapi_app/dependencies.py
- src/backend/fastapi_app/embeddings.py
- src/backend/fastapi_app/openai_clients.py
- src/backend/fastapi_app/postgres_searcher.py
- src/backend/fastapi_app/rag_advanced.py
- src/backend/fastapi_app/rag_simple.py
- src/backend/fastapi_app/routes/api_routes.py
- tests/mocks.py
There are some environments which require Python 3.9, so this PR replaces " | " syntax with typing.Optional, typing.Union instead
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
> Make repo Python 3.9 compatible

- requirements-dev.txt
- src/backend/pyproject.toml
The most recent releases caused an incompatibility with -openai, so let's pin them to be sure.
Fixes #137 
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
> Update opentelemetry reqs

- .github/workflows/app-tests.yaml
- src/backend/fastapi_app/postgres_models.py
Fixes #152 
This PR updates the indexes to use the same operator used in the queries.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
> Update HNSW indexes to use cosine operator

- evals/safety_evaluation.py
- src/backend/fastapi_app/postgres_models.py
- src/backend/fastapi_app/query_rewriter.py
- src/backend/fastapi_app/routes/api_routes.py
Fixes a few handling issues that I encountered while running safety evaluations with various models.
```
[ ] Yes
[ ] No
```
```
[X] Bugfix
[ ] Feature
```
> A few fixes from safety eval running

- .env.sample
- evals/evaluate.py
- evals/generate_ground_truth.py
- infra/main.bicep
- src/backend/fastapi_app/dependencies.py
- src/backend/fastapi_app/openai_clients.py
- src/backend/fastapi_app/routes/api_routes.py
- src/backend/fastapi_app/update_embeddings.py
- tests/conftest.py
This pull request introduces support for GitHub-hosted AI models in various parts of the codebase and includes a minor refactor to standardize the naming of embedding dimension environment variables. 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
> Add support for GitHub Models

- .github/workflows/app-tests.yaml
- infra/main.bicep
This pull request updates the `location` parameter in the `infra/main.bicep` file to restrict allowed deployment regions and add relevant metadata. The main change ensures that deployments can only be performed in regions supported by `microsoft.insights/components`.
Resource region restrictions:
* Added an `@allowed` decorator to the `location` parameter, listing all supported Azure regions for `microsoft.insights/components`. This prevents deployments in unsupported regions.
* Added an `@metadata` decorator to the `location` parameter to specify its type as 'location' for azd.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[ ] …
```
> Restrict regions due to AppInsights error
